### ISSUE TITLE
Adding a listener for reads

### ISSUE THREAD

**Issue by roly445** [MicroLite-ORM/MicroLite#404]
Hi, is there a way to add a listener for reads?

**Comment by TrevorPilley** [comment]
Not at the moment, what would the use case be?

**Comment by roly445** [comment]
I want to add some custom logging against reads against the database so I can find out what queries a user has run.  I can capture this in a separate part of the system, but to make it more flexible and dynamic I was hoping to do it as part of a listener.

**Comment by TrevorPilley** [comment]
As in logging the actual SQL or just the fact that the user has read Customer 12345?

**Comment by roly445** [comment]
Well just custom data really,  so yes like the customer id of the user
running the query, or some complex object like a user agent injected in.

**Comment by TrevorPilley** [comment]
The idea behind the listeners is to allow setting identifiers or validation or setting created/modified properties - essentially just working with an instance of an entity. So although I'm not against the idea, I do wonder if the listener API is the correct place for the capability you are after?

**Comment by TrevorPilley** [comment]
Lets try this out in MicroLite 7:

``` CSharp
public interface ISelectListener
{
    void AfterSelect(object instance);
}
```

**Comment by TrevorPilley** [comment]
Bouncing back to 7.0 from 6.3, still not 100% sure whether I like the idea of it...
