### ISSUE TITLE
.NET Core 

### ISSUE THREAD

**Issue by blendsdk** [MicroLite-ORM/MicroLite#469]
Hi,

Are there any plans to support .NET Core and building the project with VS2017?

Thanks,
Gevik.

**Comment by TrevorPilley** [comment]
Yes, it's something I'm planning on doing once .NET Core 2.0 comes around.

**Comment by blendsdk** [comment]
Thank you :) Let me know if I can be of any help.

**Comment by mtrcn** [comment]
Hi,

Is there any update about it? I'm also thinking to work on this, if you're not already working on it.

Thanks,

**Comment by TrevorPilley** [comment]
This won’t be done by supporting .NET Core, it will be done by supporting .NET Standard 2.0 potentially in MicroLite 8
