### ISSUE TITLE
SQLBuilder Bug when using the asterisk

### ISSUE THREAD

**Issue by Lenostatos** [MicroLite-ORM/MicroLite#483]
The following code prints "SELECT  FROM Tags" to the console, omitting the asterisk which then results in an invalid SQL syntax exception.

`Dim query As SqlQuery = Builder.SqlBuilder.Select("*").From(GetType(Tag)).ToSqlQuery()
Console.WriteLine(query.ToString())`

I'm using Visual Basic so maybe that's causing the problem?

**Comment by TrevorPilley** [comment]
Unable to reproduce, if it’s still an issue and you can replicate against the current develop branch then please send a PR with a failing test and I’ll take a look.
